CREATE TABLE IF NOT EXISTS logs (
  id SERIAL PRIMARY KEY,
  event VARCHAR(255) NOT NULL,
  path VARCHAR(255) NOT NULL,
  referrer VARCHAR(255),
  user_agent TEXT,
  ip VARCHAR(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);